# CS50 Nuggets Project
# Team 17 - CecsC
#
# Makefile - player directory
#

CFLAGS = -Wall -pedantic -std=c11 -ggdb -I$(L) -I$(LL) 
CC = gcc
MAKE = make

# directories 
L = ../libcs50
LL = ../support

# libraries
LIB = $(L)/libcs50.a
LIB1 = $(LL)/support.a

# programs
PROG = gridtest


grid.o: grid.h

gridcell.o: gridcell.h